version: '3'
services:
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
  api:
    # build: .
    image: ak1103/check-attendance-api
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
volumes:
  mongo-data: